### ISSUE TITLE
example command run error

### ISSUE THREAD

**Issue by ChengYunazhi** [LKremer/CAFE_fig#1] opened 2018-04-20 04:17 UTC
Hi, @LKremer 

I run for the example command and get this: 

![qq 20180420121615](https://user-images.githubusercontent.com/13846735/39030471-a83afb54-4494-11e8-96b1-5c4921d674f1.png)
how to fix it ?

All the best!
Yuanzhi

**Comment by ChengYunazhi** [comment] 2018-04-20 06:15
another question: how did cafe_fig known significant constraction or expansion in a specific gene family? It seems there is no such information in cafe output file. 

Thanks!

**Comment by LKremer** [comment] 2018-04-23 08:53
Hi @ChengYunazhi ,

The crash you posted seems to be a problem with the latest version of ete3. I've encountered it before and the only way to fix it was to downgrade to version 3.0.0b35, which works fine. Can you check which version you have installed? It should look like this in an interactive Python session (doesn't matter if it's Python3 or 2):

```
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ete3
>>> ete3.__version__
'3.0.0b35'
>>> ete3.TreeStyle()
<ete3.treeview.main.TreeStyle object at 0x7f7fc0b45278>
```

If you have a different version of ete3, I suggest you uninstall it and re-install the same version I have. E.g. like this (maybe you'll need to sudo):

```
pip uninstall ete3
pip install 'ete3==3.0.0b35'
```

Concerning your second question:
The [cafe output file ending with .cafe](https://raw.githubusercontent.com/LKremer/CAFE_fig/master/example_result.cafe) contains p-values for every family and every branch, e.g. in the example file I've linked you find this line:

> C_595143	(eda_51:413,((rpr_40:357,((((hsa_25:133,(lhu_40:132,(cfl_26:111,(pba_48:95,(sin_35:79,(aec_26:11,ace_40:11)_34:68)_35:16)_35:16)_34:21)_34:1)_34:29,ame_28:162)_33:41,nvi_31:203)_33:122,((dme_33:272,aae_35:272)_33:38,tca_28:310)_33:15)_34:32)_35:1,((((mna_27:121,cse_40:121)_33:11,zne_30:132)_33:96,bge_41:228)_35:67,lmi_39:295)_35:63)_35:55)_37	_0.000000_	**((0.022642,0.403493),(0.315218,0.623411),(0.004234,0.578184),(0.069187,0.731964),(0.063517,0.256721),(0.000024,0.794130),(0.947148,0.739724),(0.006236,0.052782),(0.380008,0.166343),(0.878440,0.831315),(0.716829,0.636580),(0.955045,0.611123),(0.920541,0.150604),(0.740349,0.907094),(0.206184,0.111754),(0.840886,0.371977),(0.516269,0.136031),(0.910094,0.371000))**

The value in _italics_ is the family-wide p-value and the **bold** values are the Viterbi p-values from CAFE.

Hope I could help,
Lukas

**Comment by altingia** [comment] 2018-05-10 11:16
Hi, LKremer,
   I've used the example input file, but got a strange summary output not as yours, it's strange that all the branch with the same numbers of expansion/contraction gene families, I went on with my own data, the same situation, I used python3.6,, and ete3 with the exact version as you proposed
[summary.pdf](https://github.com/LKremer/CAFE_fig/files/1991410/summary.pdf)
What's the mistakens

**Comment by LKremer** [comment] 2018-05-10 22:57
Hi @altingia ,

strange, that looks like a bug. It should work with the provided example file at least. I'll have a look at it once I find some time.

**Comment by LKremer** [comment] 2018-05-22 15:52
Hi @altingia ,

It looks like the problem is that the number of significant expansions/contractions are not counted properly. Can you try using the --count_all_expansions flag? This option allowed me to recreate the example figures. The summary plot will then show the number of *all* expansions (including insignificant ones) but I think this information is still useful to see the general dynamics (e.g. to see which species had a lot of expansions in total). I also used this option to create the example figures, but forgot to mention it in the readme.

This command here should work:

`./CAFE_fig.py example_result.cafe -c Isoptera=zne,mna -pb 0.05 -pf 0.05 --dump test/ -g .pdf --count_all_expansions`

Cheers,
Lukas

**Comment by jorels** [comment] 2019-04-23 08:25
Hi @altingia ,

I have been trying to use your script to parse my CAFE run but I keep getting this error: 

File "./CAFE_fig.py", line 517, in <module>
    main(**vars(args))
  File "./CAFE_fig.py", line 458, in main
    c = CAFE_fig(report_cafe, families, clades, pb, pf, dump, gfx_output_format, count_all_expansions)
  File "./CAFE_fig.py", line 86, in __init__
    self.parse_tree()
  File "./CAFE_fig.py", line 134, in parse_tree
    self.parse_phylo_tree(line)
  File "./CAFE_fig.py", line 195, in parse_phylo_tree
    self.tree = ete3.Tree(newick)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ete3/coretype/tree.py", line 210, in __init__
    read_newick(newick, root_node = self, format=format)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ete3/parser/newick.py", line 237, in read_newick
    return _read_newick_from_string(nw, root_node, matcher, format)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ete3/parser/newick.py", line 289, in _read_newick_from_string
    _read_node_data(closing_internal, current_parent, "internal", matcher, formatcode)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ete3/parser/newick.py", line 386, in _read_node_data
    raise NewickError("Unexpected newick format '%s' " %subnw[0:50])
ete3.parser.newick.NewickError: Unexpected newick format 'MOSMEL:189.761' 

What do you think I am doing wrong?

Many thanks,

Joe

**Comment by LKremer** [comment] 2019-04-23 09:59
> ete3.parser.newick.NewickError: Unexpected newick format 'MOSMEL:189.761'

Hi @jorels,
Could you upload your CAFE result file (or the first ~100 lines if it's too large) so I can check what's wrong? Or you could compare it to the example output file in this repository and see if there is anything missing or weird about yours. Which CAFE version did you use?
Best,
Lukas

**Comment by jorels** [comment] 2019-04-23 10:51
Hi Lukas,


Many thanks for getting back to me so quick.


?I have attached the first 200 lines from my CAFE output.


I haven't noticed anything wierd about my output except that in the log fiiles I had intermittent '-inf' as Scores (see attached log file).


I used CAFE version: 4.2.1. I did use an ultrameric tree to run CAFE following the steps in your tutorial.


I look forward to hearing from you soon.


Best wishes,


Joe



________________________________

**Comment by jorels** [comment] 2019-04-24 16:08
Dear Lukas,


I do hope this meets you well.


I was wondering if you were able to identify the issue with my data. Unfortunately I couldn't send the whole .cafe file because it was beyond the size I could upload via email.


If you could generate those summary results, I would find a way to send you the complete file.


I look forward to your response.


Many thanks,


Joe

________________________________

**Comment by LKremer** [comment] 2019-04-25 07:18
Hi @jorels,

I think you're just using the wrong output file. You need to use the result file and not the log file. The result file looks like this: [LKremer/CAFE_fig/master/example_result.cafe](https://raw.githubusercontent.com/LKremer/CAFE_fig/master/example_result.cafe).

Best,
Lukas

**Comment by jorels** [comment] 2019-04-25 08:28
Hi Lukas,

I did use the .cafe file.? I have been able to attach the .cafe output.

Could you please look at it and possibly run it from your end to see what I got wrong?

Many thanks for your assistance.

Jorels?


________________________________

**Comment by LKremer** [comment] 2019-04-25 16:05
Hi @jorels,

I looked at your attached file and it's clearly a very different format from the one I linked in my previous reply, you can check for yourself. Your file contains log information that CAFE prints to the screen when running, e.g. "DONE" and "Running Viterbi algorithm....". So it's not a result file. It looks like the redirected stdout. In short, check if CAFE produced a file that looks similar to the one I linked and try that one instead.

**Comment by jorels** [comment] 2019-04-25 16:38
Dear Lukas,


I have checked and the file I sent you and it is just like the link you sent me with Tree, Lambda Tree Average Expansion etc. It has no "DONE" OR "Running Viterbi algorithm.


I have attached the zipped file again. It can be seen after running gunzip.


Many thanks for all your efforts.


Jorels

________________________________

**Comment by LKremer** [comment] 2019-04-26 09:03
Hi @jorels,
I didn't receive the proper cafe file. I guess you can't just attach it via email. Can you go to github.com and upload it there instead of attaching it to a mail?
Best,
Lukas

**Comment by jorels** [comment] 2019-04-26 09:04
Hi Lukas,

Oh, sorry I didn't know about that. 

I have attached the file.

Many thanks,

Jorels
[report_run1.cafe.gz](https://github.com/LKremer/CAFE_fig/files/3120546/report_run1.cafe.gz)

**Comment by LKremer** [comment] 2019-04-29 08:08
Hi @jorels,
something is wrong with your species tree. I mean this one here: "((((((BTAQ:167.393,BTAB:167.393):100.518,(BTA1:181.171,BTA3:181.171):86.7396):143.659,DPUL:411.57):40.3558,(PEHH:378.235,PEA1:378.235):73.6904):26.9263,(((AMOS:238,DMEL:238)MOSMEL:189.761,(BMOR:171.914,MBUT:171.914):255.847):36.2032,(((REDB:306.458,PSYL:306.458):36.8365,((BEE1:193.985,CANT:193.985):62.1943,WASP:256.179):87.1155):30.3317,TBUG:373.626):90.3376):14.8877):281.205,TURT:760.057)"

The entry of MOSMEL is somehow wrongly formatted, maybe a comma is missing or something. If you paste it into e.g. http://www.trex.uqam.ca/index.php?action=newick&project=trex the entry is simply missing.

**Comment by jorels** [comment] 2019-04-30 12:33
Hi Lukas,


You are right, The entry MOSMEL was wrong and I have reran the cafe again.


However, I got a ZeroDivisionError error when running your program:


File "/Users/admin/Software/CAFE_fig/CAFE_fig.py", line 517, in <module>

    main(**vars(args))

  File "/Users/admin/Software/CAFE_fig/CAFE_fig.py", line 458, in main

    c = CAFE_fig(report_cafe, families, clades, pb, pf, dump, gfx_output_format, count_all_expansions)

  File "/Users/admin/Software/CAFE_fig/CAFE_fig.py", line 86, in __init__

    self.parse_tree()

  File "/Users/admin/Software/CAFE_fig/CAFE_fig.py", line 136, in parse_tree

    self.parse_lambdas(line)

  File "/Users/admin/Software/CAFE_fig/CAFE_fig.py", line 209, in parse_lambdas

    self.lambda_colors[i] = to_rgb(math.log(lambda_), min_l, max_l)

  File "/Users/admin/Software/CAFE_fig/CAFE_fig.py", line 62, in to_rgb

    v = (v_abs - min_v) / (max_v - min_v)  # scaled to a value between 0 and 1

ZeroDivisionError: float division by zero​


I have attached the cafe output I used in running the program.


Many thanks for your efforts.


Best wishes,


Jorels


________________________________

**Comment by njliangdong** [comment] 2019-05-22 15:16
Hi, @LKremer,
when I input command ete3.TreeStyle(), I got an error like as follow:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'TreeStyle'

I don't know how to fix it because my ete3 version has already been '3.0.0b35'

Thanks for you reply
Dong

**Comment by LKremer** [comment] 2019-09-05 13:59
Hi @jorels ,
this was the same issue as #4, it should be fixed now.

**Comment by LKremer** [comment] 2019-09-05 14:01
@njliangdong this seems to be an issue with the installation of ete3. Maybe you don't have read and execute permissions in your ete3 installation directory?

**Closed as completed by LKremer** 2019-09-05 14:01 UTC

**Comment by ajkshdkjahdka** [comment] 2020-05-15 21:44
> @njliangdong this seems to be an issue with the installation of ete3. Maybe you don't have read and execute permissions in your ete3 installation directory?

i have met the same problem, so do you have any methods to solve it  thanks !

**Comment by shiwg-eco** [comment] 2020-07-07 06:57
> 
> 
> > @njliangdong this seems to be an issue with the installation of ete3. Maybe you don't have read and execute permissions in your ete3 installation directory?
> 
> i have met the same problem, so do you have any methods to solve it thanks !

i have met the same problem too, and try to install ete3 at py27 but it's not work. so do you have methods to solve it?
best wishes
